# Generated by Django 5.0.3 on 2024-04-30 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0006_game'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Game',
        ),
    ]
