# Generated by Django 5.0.3 on 2024-04-30 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0008_pedido'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pedido',
        ),
    ]
