# Generated by Django 5.0.3 on 2024-04-30 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0010_item_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
